version: "3.8"

services:
  server:
    build: .
    container_name: streaming-server
    ports:
      - "1986:1986"
    volumes:
      - ./videos:/app/videos
    networks:
      - streaming-net
    command: ["java", "-jar", "/app/DAI-LAB-03-1.0-SNAPSHOT.jar", "Server"]
    stdin_open: true
    tty: true  # Activer un terminal interactif

  client:
    build: .
    container_name: streaming-client
    depends_on:
      - server
    networks:
      - streaming-net
    command: ["java", "-jar", "/app/DAI-LAB-03-1.0-SNAPSHOT.jar", "Client", "--host", "server", "--port", "1986"]
    stdin_open: true
    tty: true  # Activer un terminal interactif

networks:
  streaming-net:
    driver: bridge

