services:
  server:
    image: ghcr.io/HEIG-VD-S3-PW/dai-lab-03:latest
    container_name: streaming-server
    ports:
      - "1986:1986"
    volumes:
      - ./videos:/app/videos
      - ./server_data:/app/server_data
    networks:
      - streaming-net
    command: Server
    stdin_open: true
    tty: true
  client:
    image: ghcr.io/HEIG-VD-S3-PW/dai-lab-03:latest
    container_name: streaming-client
    volumes:
      - ./client_data:/app/client_data
    depends_on:
      - server
    networks:
      - streaming-net
    command: Client
    stdin_open: true
    tty: true

networks:
  streaming-net:
    driver: bridge
